export type {
  // Standard ACP types (re-exported from @agentclientprotocol/sdk)
  SessionUpdate,
  ToolCall,
  ToolCallUpdate,
  ToolKind,
  ToolCallStatus,
  ToolCallLocation,
  ToolCallContent,
  ContentChunk,
  ContentBlock,
  TextContent,
  Plan,
  PlanEntry,
  PlanUpdate,
  PlanRemoved,
  UsageUpdate,
  AvailableCommandsUpdate,
  AvailableCommand,
  CurrentModeUpdate,
  ConfigOptionUpdate,
  SessionInfoUpdate,
  PermissionOption,
  PermissionOptionKind,
  PermissionOptionId,
  RequestPermissionRequest,
  RequestPermissionOutcome,
  SelectedPermissionOutcome,
  Diff,
  Terminal,
  Cost,
  MessageId,
  // OAK convenience alias
  AcpTextBlock,
  // OAK _meta extension namespace
  OakMeta,
  // OAK extension variants
  LogUpdate,
  ArtifactUpdate,
  HistoryPageUpdate,
  AgentPhaseUpdate,
  RequestPermissionUpdate,
  AskUserUpdate,
  // OAK history types
  HistoryMessage,
  HistoryMessagePart,
  HistoryMessagePartToolCall,
  HistoryMessagePartToolResult,
  AgentPhaseName,
  // Top-level union
  AcpSessionUpdate,
  // JSON-RPC stream messages
  AcpStreamMessage,
  JsonRpcNotification,
  JsonRpcRequestMessage,
} from './types.js'
